# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [44]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression as LinReg
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, fbeta_score, confusion_matrix
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import Ridge, Lasso
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

## Regression Model Evaluation

In [7]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [3]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(X,y, test_size=0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [8]:
from sklearn.linear_model import LinearRegression as LinReg
linreg=LinReg()
linreg

LinearRegression()

In [9]:
linreg.fit(X_train, y_train)

LinearRegression()

In [10]:
linreg.coef_

array([[-1.31816311e-01,  5.19295074e-02, -4.97501348e-03,
         1.81216694e+00, -1.56992962e+01,  3.69489949e+00,
        -6.51830597e-03, -1.57580337e+00,  3.34575088e-01,
        -1.32622287e-02, -9.67324990e-01,  9.87193818e-03,
        -5.26987762e-01]])

## 3. Calculate and print R-squared for both the training and the testing set.

In [11]:
y_pred_test = linreg.predict(X_test)
y_pred_train = linreg.predict(X_train)

In [15]:
from sklearn import metrics
print('R2 - Coeficiente de Determinacion for test---------->', metrics.r2_score(y_test, y_pred_test))
print('R2 - Coeficiente de Determinacion for train--------->', metrics.r2_score(y_train, y_pred_train))

R2 - Coeficiente de Determinacion for test----------> 0.7204357810416335
R2 - Coeficiente de Determinacion for train---------> 0.7417077707643949


## 4. Calculate and print mean squared error for both the training and the testing set.

In [17]:
print('MSE - Error Cuadratico Medio for test---------->', metrics.mean_squared_error(y_test, y_pred_test))
print('MSE - Error Cuadratico Medio for train--------->', metrics.mean_squared_error(y_train, y_pred_train))

MSE - Error Cuadratico Medio for test----------> 18.087959742644482
MSE - Error Cuadratico Medio for train---------> 23.082109152958477


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [18]:
print('MSE - Error Cuadratico Medio for test---------->', metrics.mean_absolute_error(y_test, y_pred_test))
print('MSE - Error Cuadratico Medio for train--------->', metrics.mean_absolute_error(y_train, y_pred_train))

MSE - Error Cuadratico Medio for test----------> 3.2533466583413713
MSE - Error Cuadratico Medio for train---------> 3.3545489133058264


## Classification Model Evaluation

In [33]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [30]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

In [34]:
data["class"].value_counts()

0    50
1    50
2    50
Name: class, dtype: int64

In [35]:
X_train, X_test, y_train, y_test = tts(X,y, test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [39]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [40]:
log.fit(X_train,y_train)

/home/fer/miniconda3/envs/minimal_ds/lib/python3.10/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/fer/miniconda3/envs/minimal_ds/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [41]:
y_pred = log.predict(X_test)

In [42]:
y_pred_train = log.predict(X_train)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [45]:
accuracy_score(y_test, y_pred)

0.9666666666666667

In [46]:
accuracy_score(y_train, y_pred_train)

0.975

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [47]:
balanced_accuracy_score(y_test, y_pred)

0.9666666666666667

In [48]:
balanced_accuracy_score(y_train, y_pred_train)

0.9745614035087719

## 10. Calculate and print the precision score for both the training and the testing set.

In [49]:
precision_score(y_test, y_pred,average = "micro")

0.9666666666666667

In [51]:
precision_score(y_train, y_pred_train, average = 'micro')

0.975

## 11. Calculate and print the recall score for both the training and the testing set.

In [52]:
recall_score(y_test, y_pred, average = "micro")

0.9666666666666667

In [53]:
recall_score(y_train, y_pred_train, average = "micro")

0.975

## 12. Calculate and print the F1 score for both the training and the testing set.

In [54]:
f1_score(y_test, y_pred, average = "micro")

0.9666666666666667

In [55]:
f1_score(y_train, y_pred_train, average = "micro")

0.975

## 13. Generate confusion matrices for both the training and the testing set.

In [56]:
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  9,  1],
       [ 0,  0, 12]])

In [57]:
confusion_matrix(y_train, y_pred_train)

array([[42,  0,  0],
       [ 0, 38,  2],
       [ 0,  1, 37]])

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [59]:
models={
    'dis': LinearDiscriminantAnalysis(),
    'neighbors': KNeighborsClassifier(),
    'naive': GaussianNB(),
    'tree': DecisionTreeClassifier(),
    'svm': SVC(),
}

In [60]:
for name, model in models.items():
    print("entrenando... ", name)
    model.fit(X_train,y_train)

entrenando...  dis
entrenando...  neighbors
entrenando...  naive
entrenando...  tree
entrenando...  svm


/home/fer/miniconda3/envs/minimal_ds/lib/python3.10/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/fer/miniconda3/envs/minimal_ds/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/home/fer/miniconda3/envs/minimal_ds/lib/python3.10/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/fer/miniconda3/envs/minimal_ds/lib/python3.10/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vecto

In [64]:
for name, model in models.items():
    y_pred = model.predict(X_test)
    print(name)
    print('\n')
    print("Accuracy: ", accuracy_score(y_test,y_pred))
    print("Precision:", precision_score(y_test,y_pred,average = "micro"))
    print("Recall:   ", recall_score(y_test,y_pred,average = "micro"))
    print("F1:       ", f1_score(y_test, y_pred,average = "micro"))
    print('\n\n')

dis


Accuracy:  1.0
Precision: 1.0
Recall:    1.0
F1:        1.0



neighbors


Accuracy:  1.0
Precision: 1.0
Recall:    1.0
F1:        1.0



naive


Accuracy:  0.9666666666666667
Precision: 0.9666666666666667
Recall:    0.9666666666666667
F1:        0.9666666666666667



tree


Accuracy:  0.9666666666666667
Precision: 0.9666666666666667
Recall:    0.9666666666666667
F1:        0.9666666666666667



svm


Accuracy:  0.9666666666666667
Precision: 0.9666666666666667
Recall:    0.9666666666666667
F1:        0.9666666666666667



